import Groq from 'groq-sdk'

export const groq = new Groq({ apiKey: process.env.GROQ_API_KEY })

const MODEL = 'llama-3.3-70b-versatile'

const ACTION_INSTRUCTIONS = `
## YOUR ABILITY TO ADD & UPDATE DATA

When the user asks you to add, record, or update anything:
1. FIRST ask for confirmation in a short, clear sentence — e.g. "Shall I add Kirtan as a customer?" or "Ready to record this £500 sale — confirm?"
2. Include the ACTIONS block so the system is ready to execute once the user confirms

IMPORTANT: The user will see Yes/No confirmation buttons. Do NOT say "I've added..." — say "Shall I add..." because it hasn't happened yet.

At the END of your confirmation text, include:

---ACTIONS---
[{"type":"ACTION_TYPE","data":{...}}]
---END ACTIONS---

Available action types and their fields (* = required):

add_customer    → name*, email, phone, company, notes
add_employee    → name*, position*, email, department, salary (number), status (active/on_leave/inactive)
add_sale        → description*, amount* (number), date (YYYY-MM-DD), status (completed/pending/refunded)
add_expense     → description*, amount* (number), category (rent/utilities/marketing/payroll/suppliers/other), date (YYYY-MM-DD)
add_task        → title*, description, assigned_to, due_date (YYYY-MM-DD), priority (low/medium/high), status (todo/doing/completed)
add_meeting     → title*, date* (YYYY-MM-DD), attendees (array of strings), minutes, decisions (array of strings)

Rules:
- You can include multiple actions in one array
- Today's date is ${new Date().toISOString().slice(0, 10)} — use it as default when no date is given
- Do NOT include the ---ACTIONS--- block for regular questions or advice — only when adding/updating data
- If the user has already confirmed ("yes", "go ahead", "do it") earlier in the conversation and is clearly repeating, you can skip re-asking
`

export async function chatWithBusinessContext(
  messages: { role: 'user' | 'assistant' | 'system'; content: string }[],
  businessContext: string
) {
  const systemPrompt = `You are an expert business advisor AND data assistant for a business management dashboard.

You have two jobs:
1. Answer questions and give business advice based on the data below
2. Add or update business data when the user asks you to

Business data:
${businessContext}

${ACTION_INSTRUCTIONS}

How to respond:
- For questions about data: answer directly from what you see
- For open advice questions: give honest, practical business advice — flag problems, suggest next steps
- For add/update requests: do it, confirm it, include the ACTIONS block
- Be concise — no waffle`

  const response = await groq.chat.completions.create({
    model: MODEL,
    messages: [{ role: 'system', content: systemPrompt }, ...messages],
    temperature: 0.4,
    max_tokens: 1200,
  })

  return response.choices[0].message.content ?? ''
}

export async function generateBusinessSummary(businessData: string, businessName: string) {
  const prompt = `You are a business advisor. Write an honest, practical business summary for "${businessName}":

${businessData}

Structure:
## ${businessName} — Business Summary
**Date:** ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}

### Overview
2-3 sentences on overall health.

### Financials
Revenue, expenses, profit. Flag anything concerning.

### Customers & Team
Key people, any risks.

### Open Priorities
Tasks, overdue items.

### Advisor's Recommendation
Top 3 things the owner should do right now — be specific.

---
*Generated by AI Business Hub*

Use actual numbers. Be specific. Under 400 words.`

  const response = await groq.chat.completions.create({
    model: MODEL,
    messages: [{ role: 'user', content: prompt }],
    temperature: 0.5,
    max_tokens: 1500,
  })

  return response.choices[0].message.content ?? ''
}

// Parse ---ACTIONS--- block out of AI message
export function parseActions(raw: string): { message: string; actions: AIAction[] } {
  const marker = '---ACTIONS---'
  const endMarker = '---END ACTIONS---'
  const start = raw.indexOf(marker)
  const end = raw.indexOf(endMarker)

  if (start === -1) return { message: raw.trim(), actions: [] }

  const message = raw.slice(0, start).trim()
  const jsonStr = raw.slice(start + marker.length, end === -1 ? undefined : end).trim()

  try {
    const actions = JSON.parse(jsonStr) as AIAction[]
    return { message, actions: Array.isArray(actions) ? actions : [] }
  } catch {
    return { message, actions: [] }
  }
}

export interface AIAction {
  type:
    | 'add_customer' | 'add_employee' | 'add_sale'
    | 'add_expense'  | 'add_task'     | 'add_meeting'
  data: Record<string, unknown>
}
